# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wamon < Formula
  desc "CLI tool related to WAON points or services"
  homepage "https://github.com/econron/wamon"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/econron/wamon/releases/download/v0.2.1/wamon_Darwin_x86_64.tar.gz"
      sha256 "3a87f5a9b10512235e887db7fd393bb266a3cba4db09981822c3b177b5eb6236"

      def install
        bin.install "wamon"
        # もし、設定ファイルやシェルの補完スクリプトなども配布する場合は以下のように追加します
        # etc.install "path/to/your/config.yaml" => "wamon.yaml" # 設定ファイル例
        # zsh_completion.install "completions/wamon.zsh" => "_wamon" # Zsh補完例
        # bash_completion.install "completions/wamon.bash"          # Bash補完例
        # fish_completion.install "completions/wamon.fish"          # Fish補完例
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/econron/wamon/releases/download/v0.2.1/wamon_Darwin_arm64.tar.gz"
      sha256 "df4898f1a2378e1654e4162ef38c85a9e284cc15e888f1c45f3b33c28fbf34bc"

      def install
        bin.install "wamon"
        # もし、設定ファイルやシェルの補完スクリプトなども配布する場合は以下のように追加します
        # etc.install "path/to/your/config.yaml" => "wamon.yaml" # 設定ファイル例
        # zsh_completion.install "completions/wamon.zsh" => "_wamon" # Zsh補完例
        # bash_completion.install "completions/wamon.bash"          # Bash補完例
        # fish_completion.install "completions/wamon.fish"          # Fish補完例
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/econron/wamon/releases/download/v0.2.1/wamon_Linux_x86_64.tar.gz"
        sha256 "27c344917a56b2a96d2cb21ae71c54aa6fc471f91aea355325b68e2f192f112b"

        def install
          bin.install "wamon"
          # もし、設定ファイルやシェルの補完スクリプトなども配布する場合は以下のように追加します
          # etc.install "path/to/your/config.yaml" => "wamon.yaml" # 設定ファイル例
          # zsh_completion.install "completions/wamon.zsh" => "_wamon" # Zsh補完例
          # bash_completion.install "completions/wamon.bash"          # Bash補完例
          # fish_completion.install "completions/wamon.fish"          # Fish補完例
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/econron/wamon/releases/download/v0.2.1/wamon_Linux_arm64.tar.gz"
        sha256 "69454feff3dfb7441c3b3f2990573ddafd3e4820b7bf40a9e5697260b90decd6"

        def install
          bin.install "wamon"
          # もし、設定ファイルやシェルの補完スクリプトなども配布する場合は以下のように追加します
          # etc.install "path/to/your/config.yaml" => "wamon.yaml" # 設定ファイル例
          # zsh_completion.install "completions/wamon.zsh" => "_wamon" # Zsh補完例
          # bash_completion.install "completions/wamon.bash"          # Bash補完例
          # fish_completion.install "completions/wamon.fish"          # Fish補完例
        end
      end
    end
  end

  test do
    # 例1: ヘルプコマンドがエラーなく実行できればOKとする
    system "#{bin}/wamon", "--help"
    # 例2: バージョンコマンドの出力に特定の文字列が含まれるか確認する
    assert_match "wamon version", shell_output("#{bin}/wamon --version")
  end
end
