# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wamon < Formula
  desc "CLI tool related to WAON points or services"
  homepage "https://github.com/econron/wamon"
  version "0.2.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/econron/wamon/releases/download/v0.2.7/wamon_Darwin_x86_64.tar.gz"
      sha256 "9eedd5a502c00f1d18f3298825e7a182e808bf872e43506da3a16255010a5746"

      def install
        bin.install "wamon"
        # もし、設定ファイルやシェルの補完スクリプトなども配布する場合は以下のように追加します
        # etc.install "path/to/your/config.yaml" => "wamon.yaml" # 設定ファイル例
        # zsh_completion.install "completions/wamon.zsh" => "_wamon" # Zsh補完例
        # bash_completion.install "completions/wamon.bash"          # Bash補完例
        # fish_completion.install "completions/wamon.fish"          # Fish補完例
      end
    end
    on_arm do
      url "https://github.com/econron/wamon/releases/download/v0.2.7/wamon_Darwin_arm64.tar.gz"
      sha256 "71748b13ee974561bff7c7aec298dde6ec0ba61693af56cd36eb7163a5d6ce3b"

      def install
        bin.install "wamon"
        # もし、設定ファイルやシェルの補完スクリプトなども配布する場合は以下のように追加します
        # etc.install "path/to/your/config.yaml" => "wamon.yaml" # 設定ファイル例
        # zsh_completion.install "completions/wamon.zsh" => "_wamon" # Zsh補完例
        # bash_completion.install "completions/wamon.bash"          # Bash補完例
        # fish_completion.install "completions/wamon.fish"          # Fish補完例
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/econron/wamon/releases/download/v0.2.7/wamon_Linux_x86_64.tar.gz"
        sha256 "c823d83d43fe1ebf12c4a84e9cf8220231182dc2996caf47abfe559e96ca672f"

        def install
          bin.install "wamon"
          # もし、設定ファイルやシェルの補完スクリプトなども配布する場合は以下のように追加します
          # etc.install "path/to/your/config.yaml" => "wamon.yaml" # 設定ファイル例
          # zsh_completion.install "completions/wamon.zsh" => "_wamon" # Zsh補完例
          # bash_completion.install "completions/wamon.bash"          # Bash補完例
          # fish_completion.install "completions/wamon.fish"          # Fish補完例
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/econron/wamon/releases/download/v0.2.7/wamon_Linux_arm64.tar.gz"
        sha256 "a628df6640cbdec7a2912ec64639d672541936bc46a61f4b2d3fef1d0ef64af7"

        def install
          bin.install "wamon"
          # もし、設定ファイルやシェルの補完スクリプトなども配布する場合は以下のように追加します
          # etc.install "path/to/your/config.yaml" => "wamon.yaml" # 設定ファイル例
          # zsh_completion.install "completions/wamon.zsh" => "_wamon" # Zsh補完例
          # bash_completion.install "completions/wamon.bash"          # Bash補完例
          # fish_completion.install "completions/wamon.fish"          # Fish補完例
        end
      end
    end
  end

  test do
    # system コマンドのパス指定を推奨スタイルに変更
    system bin/"wamon", "--help"

    # shell_output はコマンド全体を文字列として渡すため、
    # こちらは "#{bin}/wamon --version" のままでも audit で指摘されないことが多いです。
    # もしこちらも指摘されるようであれば、別のテスト方法を検討します。
    assert_match "wamon version", shell_output("#{bin}/wamon --version")
  end
end
